[package]
name = "byteable"
version = "0.9.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/PaulDepping/byteable"
description = "A Rust crate for convenient serialization and deserialization of byte-oriented data."
readme = "README.md"

[features]
all = ["derive", "tokio"]
default = ["derive"]
derive = ["dep:byteable_derive"]
tokio = ["dep:tokio"]

[dependencies]
byteable_derive = { version = "0.2.0", path = "byteable_derive", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
